[package]
name = "spotter"
description = "Library to handle exceptions"
version = "0.0.1"
edition = "2021"
authors = ["LeviLovie"]

[dependencies]
backtrace = "0.3.74"
colored = "2.1.0"
libc = "0.2.159"
signal-hook = "0.3.17"
